AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/**/*' # TravisCI
    - 'gemfiles/vendor/**/*' # TravisCI

# The fixed indentation style is rational. To align with the first parameters
# is arguably friendly, but makes for long lines and obscures control flow.
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Both the leading and trailing styles can be argued for. Singlebrook has
# chosen the trailing style.
Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: false
