cache: bundler
language: ruby
before_install:
  - gem update --system
  - gem install bundler
script: "bundle exec rake rubocop spec"
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile